### ISSUE TITLE
Trailblazer Operation standalone fails with uninitialized constant Trailblazer::Operation::Result::Forwardable

### ISSUE THREAD

**Issue by the-spectator** [trailblazer/trailblazer-operation#42]
I was trying to use trailblazer outside of rails but it was not able to load `forwardable` module hence failing to work.

## Steps to reproduce
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Activate the gem you are reporting the issue against.
  gem 'trailblazer', '~> 2.1'
  gem 'rspec'
end

require "trailblazer/operation"

class HelloOperation < Trailblazer::Operation
  step :hello_world

  def hello_world(ctx, **)
    ctx[:result] = "Hello World!"
  end
end

require 'rspec'

describe HelloOperation do
  it "returns hello world" do
    result = described_class.()

    expect(result.success?).to eq(true)
    expect(result[:result]).to eq("Hello World!")
  end
end

```
#### Expected behavior
Test to pass

#### Actual behavior
Spec fails with the exception with `uninitialized constant Trailblazer::Operation::Result::Forwardable`

#### System configuration
Trailblazer version: 2.1.0
Ruby version:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by seuros** [comment]
I would like to stacktrace please.

**Comment by the-spectator** [comment]
@seuros I have created #43 to fix the issue, please review :pray:

#### Traceback
```ruby
Traceback (most recent call last):
	16: from day1/bug.rb:3:in `<main>'
	15: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/inline.rb:54:in `gemfile'
	14: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/settings.rb:124:in `temporary'
	13: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/inline.rb:70:in `block in gemfile'
	12: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:58:in `require'
	11: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:58:in `each'
	10: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:69:in `block in require'
	 9: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:69:in `each'
	 8: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	 7: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/bundler-2.1.2/lib/bundler/runtime.rb:74:in `require'
	 6: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-2.1.0/lib/trailblazer.rb:2:in `<top (required)>'
	 5: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-2.1.0/lib/trailblazer.rb:2:in `require'
	 4: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-operation-0.6.2/lib/trailblazer/operation.rb:67:in `<top (required)>'
	 3: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-operation-0.6.2/lib/trailblazer/operation.rb:67:in `require'
	 2: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-operation-0.6.2/lib/trailblazer/operation/result.rb:2:in `<top (required)>'
	 1: from /home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-operation-0.6.2/lib/trailblazer/operation/result.rb:3:in `<class:Operation>'
/home/akshay/.rvm/gems/ruby-2.6.5/gems/trailblazer-operation-0.6.2/lib/trailblazer/operation/result.rb:26:in `<class:Result>': uninitialized constant Trailblazer::Operation::Result::Forwardable (NameError)

```
